// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubefs/cubefs/sdk/master (interfaces: ClientAPIInterface)

// Package objectnode is a generated GoMock package.
package objectnode

import (
	reflect "reflect"

	proto "github.com/cubefs/cubefs/proto"
	master "github.com/cubefs/cubefs/sdk/master"
	gomock "github.com/golang/mock/gomock"
)

// MockClientAPIInterface is a mock of ClientAPIInterface interface.
type MockClientAPIInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientAPIInterfaceMockRecorder
}

// MockClientAPIInterfaceMockRecorder is the mock recorder for MockClientAPIInterface.
type MockClientAPIInterfaceMockRecorder struct {
	mock *MockClientAPIInterface
}

// NewMockClientAPIInterface creates a new mock instance.
func NewMockClientAPIInterface(ctrl *gomock.Controller) *MockClientAPIInterface {
	mock := &MockClientAPIInterface{ctrl: ctrl}
	mock.recorder = &MockClientAPIInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAPIInterface) EXPECT() *MockClientAPIInterfaceMockRecorder {
	return m.recorder
}

// GetDataPartitions mocks base method.
func (m *MockClientAPIInterface) GetDataPartitions(arg0 string) (*proto.DataPartitionsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataPartitions", arg0)
	ret0, _ := ret[0].(*proto.DataPartitionsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataPartitions indicates an expected call of GetDataPartitions.
func (mr *MockClientAPIInterfaceMockRecorder) GetDataPartitions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataPartitions", reflect.TypeOf((*MockClientAPIInterface)(nil).GetDataPartitions), arg0)
}

// GetMetaPartition mocks base method.
func (m *MockClientAPIInterface) GetMetaPartition(arg0 uint64) (*proto.MetaPartitionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaPartition", arg0)
	ret0, _ := ret[0].(*proto.MetaPartitionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaPartition indicates an expected call of GetMetaPartition.
func (mr *MockClientAPIInterfaceMockRecorder) GetMetaPartition(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaPartition", reflect.TypeOf((*MockClientAPIInterface)(nil).GetMetaPartition), arg0)
}

// GetMetaPartitions mocks base method.
func (m *MockClientAPIInterface) GetMetaPartitions(arg0 string) ([]*proto.MetaPartitionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaPartitions", arg0)
	ret0, _ := ret[0].([]*proto.MetaPartitionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaPartitions indicates an expected call of GetMetaPartitions.
func (mr *MockClientAPIInterfaceMockRecorder) GetMetaPartitions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaPartitions", reflect.TypeOf((*MockClientAPIInterface)(nil).GetMetaPartitions), arg0)
}

// GetPreLoadDataPartitions mocks base method.
func (m *MockClientAPIInterface) GetPreLoadDataPartitions(arg0 string) (*proto.DataPartitionsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreLoadDataPartitions", arg0)
	ret0, _ := ret[0].(*proto.DataPartitionsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreLoadDataPartitions indicates an expected call of GetPreLoadDataPartitions.
func (mr *MockClientAPIInterfaceMockRecorder) GetPreLoadDataPartitions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreLoadDataPartitions", reflect.TypeOf((*MockClientAPIInterface)(nil).GetPreLoadDataPartitions), arg0)
}

// GetVolume mocks base method.
func (m *MockClientAPIInterface) GetVolume(arg0, arg1 string) (*proto.VolView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolume", arg0, arg1)
	ret0, _ := ret[0].(*proto.VolView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolume indicates an expected call of GetVolume.
func (mr *MockClientAPIInterfaceMockRecorder) GetVolume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolume", reflect.TypeOf((*MockClientAPIInterface)(nil).GetVolume), arg0, arg1)
}

// GetVolumeStat mocks base method.
func (m *MockClientAPIInterface) GetVolumeStat(arg0 string) (*proto.VolStatInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeStat", arg0)
	ret0, _ := ret[0].(*proto.VolStatInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeStat indicates an expected call of GetVolumeStat.
func (mr *MockClientAPIInterfaceMockRecorder) GetVolumeStat(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeStat", reflect.TypeOf((*MockClientAPIInterface)(nil).GetVolumeStat), arg0)
}

// GetVolumeWithAuthnode mocks base method.
func (m *MockClientAPIInterface) GetVolumeWithAuthnode(arg0, arg1, arg2 string, arg3 master.Decoder) (*proto.VolView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeWithAuthnode", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*proto.VolView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeWithAuthnode indicates an expected call of GetVolumeWithAuthnode.
func (mr *MockClientAPIInterfaceMockRecorder) GetVolumeWithAuthnode(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeWithAuthnode", reflect.TypeOf((*MockClientAPIInterface)(nil).GetVolumeWithAuthnode), arg0, arg1, arg2, arg3)
}

// GetVolumeWithoutAuthKey mocks base method.
func (m *MockClientAPIInterface) GetVolumeWithoutAuthKey(arg0 string) (*proto.VolView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeWithoutAuthKey", arg0)
	ret0, _ := ret[0].(*proto.VolView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeWithoutAuthKey indicates an expected call of GetVolumeWithoutAuthKey.
func (mr *MockClientAPIInterfaceMockRecorder) GetVolumeWithoutAuthKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeWithoutAuthKey", reflect.TypeOf((*MockClientAPIInterface)(nil).GetVolumeWithoutAuthKey), arg0)
}
