// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubefs/cubefs/sdk/master (interfaces: NodeAPIInterface)

// Package objectnode is a generated GoMock package.
package objectnode

import (
	reflect "reflect"

	proto "github.com/cubefs/cubefs/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockNodeAPIInterface is a mock of NodeAPIInterface interface.
type MockNodeAPIInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNodeAPIInterfaceMockRecorder
}

// MockNodeAPIInterfaceMockRecorder is the mock recorder for MockNodeAPIInterface.
type MockNodeAPIInterfaceMockRecorder struct {
	mock *MockNodeAPIInterface
}

// NewMockNodeAPIInterface creates a new mock instance.
func NewMockNodeAPIInterface(ctrl *gomock.Controller) *MockNodeAPIInterface {
	mock := &MockNodeAPIInterface{ctrl: ctrl}
	mock.recorder = &MockNodeAPIInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeAPIInterface) EXPECT() *MockNodeAPIInterfaceMockRecorder {
	return m.recorder
}

// AddDataNode mocks base method.
func (m *MockNodeAPIInterface) AddDataNode(arg0, arg1 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDataNode", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDataNode indicates an expected call of AddDataNode.
func (mr *MockNodeAPIInterfaceMockRecorder) AddDataNode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataNode", reflect.TypeOf((*MockNodeAPIInterface)(nil).AddDataNode), arg0, arg1)
}

// AddLcNode mocks base method.
func (m *MockNodeAPIInterface) AddLcNode(arg0 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLcNode", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLcNode indicates an expected call of AddLcNode.
func (mr *MockNodeAPIInterfaceMockRecorder) AddLcNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLcNode", reflect.TypeOf((*MockNodeAPIInterface)(nil).AddLcNode), arg0)
}

// AddMetaNode mocks base method.
func (m *MockNodeAPIInterface) AddMetaNode(arg0, arg1 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetaNode", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMetaNode indicates an expected call of AddMetaNode.
func (mr *MockNodeAPIInterfaceMockRecorder) AddMetaNode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetaNode", reflect.TypeOf((*MockNodeAPIInterface)(nil).AddMetaNode), arg0, arg1)
}

// DataNodeDecommission mocks base method.
func (m *MockNodeAPIInterface) DataNodeDecommission(arg0 string, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataNodeDecommission", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DataNodeDecommission indicates an expected call of DataNodeDecommission.
func (mr *MockNodeAPIInterfaceMockRecorder) DataNodeDecommission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataNodeDecommission", reflect.TypeOf((*MockNodeAPIInterface)(nil).DataNodeDecommission), arg0, arg1)
}

// DataNodeMigrate mocks base method.
func (m *MockNodeAPIInterface) DataNodeMigrate(arg0, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataNodeMigrate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DataNodeMigrate indicates an expected call of DataNodeMigrate.
func (mr *MockNodeAPIInterfaceMockRecorder) DataNodeMigrate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataNodeMigrate", reflect.TypeOf((*MockNodeAPIInterface)(nil).DataNodeMigrate), arg0, arg1, arg2)
}

// GetDataNode mocks base method.
func (m *MockNodeAPIInterface) GetDataNode(arg0 string) (*proto.DataNodeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataNode", arg0)
	ret0, _ := ret[0].(*proto.DataNodeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataNode indicates an expected call of GetDataNode.
func (mr *MockNodeAPIInterfaceMockRecorder) GetDataNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataNode", reflect.TypeOf((*MockNodeAPIInterface)(nil).GetDataNode), arg0)
}

// GetMetaNode mocks base method.
func (m *MockNodeAPIInterface) GetMetaNode(arg0 string) (*proto.MetaNodeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetaNode", arg0)
	ret0, _ := ret[0].(*proto.MetaNodeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaNode indicates an expected call of GetMetaNode.
func (mr *MockNodeAPIInterfaceMockRecorder) GetMetaNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetaNode", reflect.TypeOf((*MockNodeAPIInterface)(nil).GetMetaNode), arg0)
}

// MetaNodeDecommission mocks base method.
func (m *MockNodeAPIInterface) MetaNodeDecommission(arg0 string, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetaNodeDecommission", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MetaNodeDecommission indicates an expected call of MetaNodeDecommission.
func (mr *MockNodeAPIInterfaceMockRecorder) MetaNodeDecommission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetaNodeDecommission", reflect.TypeOf((*MockNodeAPIInterface)(nil).MetaNodeDecommission), arg0, arg1)
}

// MetaNodeMigrate mocks base method.
func (m *MockNodeAPIInterface) MetaNodeMigrate(arg0, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetaNodeMigrate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MetaNodeMigrate indicates an expected call of MetaNodeMigrate.
func (mr *MockNodeAPIInterfaceMockRecorder) MetaNodeMigrate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetaNodeMigrate", reflect.TypeOf((*MockNodeAPIInterface)(nil).MetaNodeMigrate), arg0, arg1, arg2)
}

// ResponseDataNodeTask mocks base method.
func (m *MockNodeAPIInterface) ResponseDataNodeTask(arg0 *proto.AdminTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseDataNodeTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResponseDataNodeTask indicates an expected call of ResponseDataNodeTask.
func (mr *MockNodeAPIInterfaceMockRecorder) ResponseDataNodeTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseDataNodeTask", reflect.TypeOf((*MockNodeAPIInterface)(nil).ResponseDataNodeTask), arg0)
}

// ResponseLcNodeTask mocks base method.
func (m *MockNodeAPIInterface) ResponseLcNodeTask(arg0 *proto.AdminTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseLcNodeTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResponseLcNodeTask indicates an expected call of ResponseLcNodeTask.
func (mr *MockNodeAPIInterfaceMockRecorder) ResponseLcNodeTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseLcNodeTask", reflect.TypeOf((*MockNodeAPIInterface)(nil).ResponseLcNodeTask), arg0)
}

// ResponseMetaNodeTask mocks base method.
func (m *MockNodeAPIInterface) ResponseMetaNodeTask(arg0 *proto.AdminTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseMetaNodeTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResponseMetaNodeTask indicates an expected call of ResponseMetaNodeTask.
func (mr *MockNodeAPIInterfaceMockRecorder) ResponseMetaNodeTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseMetaNodeTask", reflect.TypeOf((*MockNodeAPIInterface)(nil).ResponseMetaNodeTask), arg0)
}
