version: '2.1'

networks:
    extnetwork:
      ipam:
         config:
         - subnet: 192.168.0.0/24
           gateway: 192.168.0.1

services:
    monitor:
        image: chubaofs/cfs-base:dev-1.0
        depends_on:
            - consul
            - prometheus
            - grafana
        networks:
            extnetwork:

    servers:
        image: chubaofs/cfs-base:dev-1.0
        depends_on:
            - masters
            - metanodes
            - datanodes
        networks:
            extnetwork:

    masters:
        image: chubaofs/cfs-base:dev-1.0
        depends_on:
            - master1
            - master2
            - master3
        networks:
            extnetwork:

    metanodes:
        image: chubaofs/cfs-base:dev-1.0
        depends_on:
            - metanode1
            - metanode2
            - metanode3
        networks:
            extnetwork:

    datanodes:
        image: chubaofs/cfs-base:dev-1.0
        depends_on:
            - datanode1
            - datanode2
            - datanode3
            - datanode4
        networks:
            extnetwork:

    master1:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "5901"
            - "5902"
            - "17010"
            - "17020"
            - 9500
        volumes:
            - ./bin:/cfs/bin
            - ./conf/master1.json:/cfs/conf/master.json
            - ./script/start_master.sh:/cfs/script/start.sh
        command: /bin/sh /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.11

    master2:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "5901"
            - "5902"
            - "17010"
            - "17020"
            - 9500
        volumes:
            - ./bin:/cfs/bin
            - ./conf/master2.json:/cfs/conf/master.json
            - ./script/start_master.sh:/cfs/script/start.sh
        command: /bin/sh /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.12
    master3:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "5901"
            - "5902"
            - "17010"
            - "17020"
            - 9500
        volumes:
            - ./bin:/cfs/bin
            - ./conf/master3.json:/cfs/conf/master.json
            - ./script/start_master.sh:/cfs/script/start.sh
        command: /bin/sh /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.13

    metanode1:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "17210"
            - "17220"
            - "17230"
            - "17240"
            - 9500
        volumes:
            - ./bin:/cfs/bin
            - ./conf/metanode.json:/cfs/conf/metanode.json
            - ./script/start_meta.sh:/cfs/script/start.sh
        command: /bin/bash /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.21

    metanode2:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "17210"
            - "17220"
            - "17230"
            - "17240"
            - 9500
        volumes:
            - ./bin:/cfs/bin
            - ./conf/metanode.json:/cfs/conf/metanode.json
            - ./script/start_meta.sh:/cfs/script/start.sh
        command: /bin/bash /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.22

    metanode3:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "17210"
            - "17220"
            - "17230"
            - "17240"
            - 9500
        volumes:
            - ./bin:/cfs/bin
            - ./conf/metanode.json:/cfs/conf/metanode.json
            - ./script/start_meta.sh:/cfs/script/start.sh
        command: /bin/bash /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.23

    datanode1:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "17310"
            - "17320"
            - "17330"
            - "17340"
            - 9500
        volumes:
            - ${DiskPath:-./disk}/1:/cfs/disk
            - ./bin:/cfs/bin
            - ./conf/datanode.json:/cfs/conf/datanode.json
            - ./script/start_datanode.sh:/cfs/script/start.sh
        command: /bin/bash /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.31

    datanode2:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "17310"
            - "17320"
            - "17330"
            - "17340"
            - 9500
        volumes:
            - ${DiskPath:-./disk}/2:/cfs/disk
            - ./bin:/cfs/bin
            - ./conf/datanode.json:/cfs/conf/datanode.json
            - ./script/start_datanode.sh:/cfs/script/start.sh
        command: /bin/sh /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.32

    datanode3:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "17310"
            - "17320"
            - "17330"
            - "17340"
            - 9500
        volumes:
            - ${DiskPath:-./disk}/3:/cfs/disk
            - ./bin:/cfs/bin
            - ./conf/datanode.json:/cfs/conf/datanode.json
            - ./script/start_datanode.sh:/cfs/script/start.sh
        command: /bin/sh /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.33

    datanode4:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - "17310"
            - "17320"
            - "17330"
            - "17340"
            - 9500
        volumes:
            - ${DiskPath:-./disk}/4:/cfs/disk
            - ./bin:/cfs/bin
            - ./conf/datanode.json:/cfs/conf/datanode.json
            - ./script/start_datanode.sh:/cfs/script/start.sh
        command: /bin/sh /cfs/script/start.sh
        restart: on-failure
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.34

    client:
        image: chubaofs/cfs-base:dev-1.0
        ports:
            - 9500
        volumes:
            - ./bin:/cfs/bin
            - ./conf/client.json:/cfs/conf/client.json
            - ./script/run_test.sh:/cfs/script/start.sh
            - ./script/start_client.sh:/cfs/script/start_client.sh
            - ./ltp/runtest/fs:/opt/ltp/runtest/fs
        privileged: true
        devices:
            - /dev/fuse:/dev/fuse:rwm
        cap_add:
            - SYS_ADMIN
        command: /bin/bash /cfs/script/start.sh
        networks:
            extnetwork:

    consul:
        image: consul:1.5
        ports:
            - 8500:8500
        volumes:
            - ./monitor:/monitor
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.101

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        privileged: true
        networks:
            extnetwork:
                ipv4_address: 192.168.0.102

    grafana:
        image: grafana/grafana:6.2.0
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=123456
        ports:
            - 3000:3000
        volumes:
            - ./monitor/grafana/grafana.ini:/etc/grafana/grafna.ini
            - ./monitor/grafana/provisioning:/etc/grafana/provisioning
            - ./monitor/grafana/init.sh:/grafana/init.sh
        privileged: true
        #command: /bin/bash
        networks:
            extnetwork:

    build:
        image: chubaofs/cfs-base:dev-1.0
        volumes:
            - ../:/go/src/github.com/cubefs/cubefs/
        command:
            - bash
            - "-c"
            - >-
              set -e;
              mkdir -p /go/src/github.com/cubefs/cubefs/docker/bin &&
              echo -n 'build server ' ;
              cd /go/src/github.com/cubefs/cubefs/cmd && bash ./build.sh && mv cfs-server /go/src/github.com/cubefs/cubefs/docker/bin/cfs-server && echo "success" || echo "failed" ;
              echo -n 'build client ' ;
              cd /go/src/github.com/cubefs/cubefs/client && bash ./build.sh && mv cfs-client /go/src/github.com/cubefs/cubefs/docker/bin/cfs-client && echo 'success' || echo "failed" ;
        networks:
            extnetwork:
