# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'docs-zh/**'
      - '**.md'
  pull_request:
    branches:
      - master
      - develop-*
    paths-ignore:
      # - 'blobstore/**'
      # - '.github/**'
      # - 'docs/**'
      # - 'docs-zh/**'
      # - '**.md'

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go Version 1.17.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check gofmt
        run: |
            docker/run_docker.sh -f

      - name: Unit and Scenario tests
        run: |
          docker/run_docker.sh -t
          docker/run_docker.sh --scenariotest

      - name: Pack docker_data
        if: ${{ always() }}
        run: |
            pushd docker
            sudo tar --exclude='docker_data/datanode*/disk' --exclude='docker_data/disk' -czvf docker_data.tar.gz docker_data
            popd

      - name: Upload docker_data.tar.gz
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: docker_data
          path: docker/docker_data.tar.gz
          retention-days: 7

      - name: Upload codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
